import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { validateEpisodes } from './validate-episodes.mjs';

const id='cam_0123456789abcdef01234567', cid='cpc_0123456789abcdef01234567';
const candidate={candidate_id:cid,source_archive:'group-a',anchor:{corpus_message_id:id},context_before:[],context_after:[]};
function episode(){return {schema_version:'qe.v1',candidate_id:cid,episode_id:'qe_0123456789abcdef01234567',validity:{status:'valid',reasons:[]},canonical_question_zh:'问题？',canonical_question_en:'A question?',source:{source_group_key:'group-a',message_ids:[id],first_at:'2026-01-01T00:00:00Z',last_at:'2026-01-01T00:00:00Z',timezone_basis:'utc'},question:{intent:'确认事项',form:'explicit',category:'other',scope:null},entities:[],tags:[],evidence:{question:[{corpus_message_id:id,role:'question',supports:['q1']}],answer:[],excluded:[]},answer:{status:'unanswered',synthesis_zh:null,claims:[],caveats:[]},answer_evidence_ids:[],temporal:{class:'unknown',as_of:null,valid_from:null,valid_until:null,cohort_or_cycle:null,relative_date_resolution:'not_applicable',needs_current_verification:true,evidence_ids:[id]},time_sensitive:true,media_dependency:'none',media:{dependency:'none',media_ids:[],readability:'not_applicable',claims_affected:[]},conflict:{present:false,claim_ids:[],resolution:'none'},privacy:{risk:'low',actions:['none'],safe_to_surface:false},confidence:{overall:0,question:0.5,answer:0,provenance:0.95,temporal:0.2,privacy:0.9},decision:{label:'hold',reasons:['unanswered_open_question'],review_required:true}}}
test('merges valid hold into episodes and writes manifest',async()=>{const d=await mkdtemp(join(tmpdir(),'qe-'));try{const i=join(d,'i'),c=join(d,'c'),o=join(d,'o');await writeFile(i,JSON.stringify(episode())+'\n');await writeFile(c,JSON.stringify(candidate)+'\n');const m=await validateEpisodes({input:i,candidates:c,output:o});assert.equal(m.counts.episodes,1);assert.equal((await readFile(join(o,'episodes.jsonl'),'utf8')).trim().length>0,true);}finally{await rm(d,{recursive:true,force:true})}});
test('fails closed on an evidence id outside candidate window',async()=>{const d=await mkdtemp(join(tmpdir(),'qe-'));try{const i=join(d,'i'),c=join(d,'c'),o=join(d,'o'),e=episode();e.source.message_ids=['cam_abcdefabcdefabcdefabcdef'];await writeFile(i,JSON.stringify(e));await writeFile(c,JSON.stringify(candidate));await assert.rejects(validateEpisodes({input:i,candidates:c,output:o}),/outside candidate source/)}finally{await rm(d,{recursive:true,force:true})}});
