import { Lang } from '@/i18n/translations';

const copy = {
  en: {
    page: {
      eyebrow: 'RUNIPS / ACCOUNT',
      title: 'Account',
      intro: 'Choose the public identity used for Community topics and replies. Your sign-in email and Google identity stay private.',
    },
    signedOut: {
      title: 'Sign in or create an account',
      description: 'A Google account is required for a persistent Community profile.',
      action: 'Continue to sign in',
    },
    unavailable: {
      title: 'Account profiles are temporarily unavailable',
      description: 'RunIPS could not load the account-profile service. Please try again later.',
    },
    anonymous: {
      title: 'Upgrade this anonymous account',
      description: 'Link Google to keep this account’s existing reviews and turn it into a persistent Community account.',
      action: 'Upgrade with Google',
      loading: 'Redirecting to Google…',
      disabled: 'Google sign-in has not been configured on this environment yet.',
    },
    profile: {
      title: 'Public Community profile',
      preview: 'Preview',
      displayName: 'Display name',
      displayNameHint: 'Public on your Community topics, replies and profile. It does not need to be your legal name.',
      username: 'Username',
      usernameHint: 'Issued automatically when the account is created. It is fixed, so links and citations to your posts keep working.',
      displayNameLocked: 'Set during registration and fixed afterwards, so people you have talked to keep recognising you.',
      avatar: 'Avatar colour',
      avatarHint: 'RunIPS uses a lightweight initial avatar. No Google photo is imported or displayed.',
      save: 'Save profile',
      saving: 'Saving…',
      saved: 'Profile saved.',
      validationUsername: 'Enter 3–30 lowercase letters, numbers or underscores.',
      validationName: 'Enter a display name between 1 and 40 characters.',
      usernameTaken: 'That username is already in use.',
      failed: 'The profile could not be saved. Please try again.',
      required: 'Complete this profile before creating Community topics or replies.',
      continue: 'Continue',
    },
    identity: {
      title: 'Private sign-in identity',
      email: 'Google email',
      emailPrivate: 'Visible only to you and authorised RunIPS operators.',
      googleLinked: 'Google identity linked',
      googleMissing: 'Google identity not linked',
      badgeMeaning: 'This badge confirms a verified email address on waseda.jp or a sub-domain of it. It does not prove current student or IPS status.',
    },
    data: {
      title: 'Account and data',
      description: 'Review what is linked to this account or permanently erase it.',
      delete: 'Delete account and data',
    },
    publicProfile: {
      eyebrow: 'RUNIPS / MEMBER',
      joined: 'Joined {date}',
      topics: 'Topics',
      replies: 'Replies',
      back: 'Back to Community',
      invalidTitle: 'Invalid profile link',
      invalidDescription: 'This link does not contain a valid username.',
      missingTitle: 'Profile not found',
      missingDescription: 'The member may not have completed a public profile, or the account may have been deleted.',
      unavailableTitle: 'Profiles are temporarily unavailable',
      unavailableDescription: 'The profile module has not been installed on this environment.',
      errorTitle: 'Profile could not be loaded',
      errorDescription: 'RunIPS could not load this member profile. Please try again later.',
      loading: 'Loading profile…',
    },
  },
  zh: {
    page: {
      eyebrow: 'RUNIPS / ACCOUNT',
      title: '账号',
      intro: '设置用于交流中心主题和回复的公开身份。登录邮箱和 Google 身份不会公开。',
    },
    signedOut: {
      title: '登录或创建账号',
      description: '持久的交流中心个人资料需要使用 Google 账号。',
      action: '前往登录',
    },
    unavailable: {
      title: '账号资料暂不可用',
      description: 'RunIPS 暂时无法载入账号资料服务，请稍后重试。',
    },
    anonymous: {
      title: '升级当前匿名账号',
      description: '关联 Google 后可以保留该账号已有的评价，并将其升级为可长期使用的交流中心账号。',
      action: '使用 Google 升级',
      loading: '正在跳转 Google…',
      disabled: '当前环境还没有配置 Google 登录。',
    },
    profile: {
      title: '公开交流中心资料',
      preview: '预览',
      displayName: '昵称',
      displayNameHint: '会显示在交流中心主题、回复和个人页面；不需要使用真实姓名。',
      username: '用户名',
      usernameHint: '创建账号时自动分配，不可更改，以保证指向你发帖的链接和引用始终有效。',
      displayNameLocked: '注册时设定，之后不可更改，以免认识你的人认不出来。',
      avatar: '头像颜色',
      avatarHint: 'RunIPS 使用轻量的首字母头像，不会导入或显示 Google 头像。',
      save: '保存资料',
      saving: '保存中…',
      saved: '资料已保存。',
      validationUsername: '请输入 3–30 个小写英文字母、数字或下划线。',
      validationName: '请输入 1–40 个字符的昵称。',
      usernameTaken: '该用户名已被使用。',
      failed: '资料保存失败，请稍后重试。',
      required: '发布交流中心主题或回复前需要先完成此资料。',
      continue: '继续',
    },
    identity: {
      title: '私密登录身份',
      email: 'Google 邮箱',
      emailPrivate: '只有你本人和获得授权的 RunIPS 运维人员可以查看。',
      googleLinked: '已关联 Google 身份',
      googleMissing: '尚未关联 Google 身份',
      badgeMeaning: '该标识仅确认已验证的 waseda.jp 域名（含子域）邮箱，不代表现役学生或 IPS 身份。',
    },
    data: {
      title: '账号与数据',
      description: '查看与该账号关联的数据，或将其永久删除。',
      delete: '删除账号与数据',
    },
    publicProfile: {
      eyebrow: 'RUNIPS / MEMBER',
      joined: '加入于 {date}',
      topics: '主题',
      replies: '回复',
      back: '返回交流中心',
      invalidTitle: '个人页面链接无效',
      invalidDescription: '该链接没有包含有效用户名。',
      missingTitle: '找不到个人资料',
      missingDescription: '该成员可能尚未完成公开资料，或账号已经删除。',
      unavailableTitle: '个人资料暂不可用',
      unavailableDescription: '当前环境还没有安装个人资料模块。',
      errorTitle: '个人资料载入失败',
      errorDescription: 'RunIPS 暂时无法载入该成员资料，请稍后重试。',
      loading: '正在加载个人资料…',
    },
  },
} as const;

export function getAccountCopy(lang: Lang) {
  return copy[lang];
}
