export const travelCopy = {
  en: {
    eyebrow: 'AIR TRAVEL TO IPS',
    title: 'Build a route to Fukuoka.',
    introduction:
      'Search real same-day flight options into FUK or KKJ, compare each connection pattern, then inspect the exact itinerary before booking.',
    flightsStage: 'Live flight search',
    documentsStage: 'Transit document screen',
    localStage: 'Airport to campus — later',
    formTitle: 'Search the airline journey',
    formDescription: 'One-way economy results are grouped by direct route or ordered transfer airports.',
    originLabel: 'Home airport',
    originPlaceholder: 'e.g. Changsha or CSX',
    originHelp: 'Type a city name or airport code, then choose from the list.',
    invalidOrigin: 'Pick a departure airport from the list, or type its three-letter code. It must differ from the destination.',
    destinationLabel: 'Arrival airport',
    fukOption: 'FUK — Fukuoka',
    kkjOption: 'KKJ — Kitakyushu',
    dateLabel: 'Departure date',
    dateHelp: 'Searches one specific day.',
    invalidDate: 'Choose today or a future date within the next year.',
    passportLabel: 'Passport issued by',
    passportPlaceholder: 'e.g. China',
    passportHelp: 'Used only in this browser for the transfer screen.',
    ticketLabel: 'Ticket arrangement',
    ticketSingle: 'One protected booking',
    ticketSeparate: 'Separate tickets / self-transfer',
    ticketUnknown: 'Not sure yet',
    baggageLabel: 'Baggage plan',
    baggageThrough: 'Checked through to the final airport',
    baggageCollect: 'Collect and check in again',
    baggageCabin: 'Cabin baggage only',
    baggageUnknown: 'Not sure yet',
    searchAction: 'Search flights',
    searching: 'Searching live flights…',
    studentStatus:
      'Japanese student residence status is assumed. The document screen concerns only transfer points before arrival in Japan.',
    searchDisclosure:
      'Origin, destination and date are sent through RunIPS to SerpApi. Passport, ticket and baggage answers remain in this browser.',
    initialTitle: 'Your route choices will appear here',
    initialBody: 'Choose an airport and date to compare direct and connecting itineraries. No sample flights are shown.',
    routeComparison: 'Route choices',
    comparisonDescription: 'Each card is the lowest-priced returned itinerary for that connection pattern.',
    routesFound: (count: number) => `${count} route ${count === 1 ? 'pattern' : 'patterns'}`,
    offersFound: (count: number) => `${count} returned ${count === 1 ? 'itinerary' : 'itineraries'}`,
    direct: 'Direct',
    via: (codes: string) => `Via ${codes}`,
    from: 'from',
    alternativeCount: (count: number) => `${count} ${count === 1 ? 'option' : 'options'} in this pattern`,
    itinerary: 'Cheapest itinerary in this pattern',
    totalJourney: 'Total journey',
    connection: 'connection',
    connections: 'connections',
    overnight: 'Overnight',
    operatedBy: 'Airline',
    operatingCarrier: 'Operated by',
    aircraft: 'Aircraft',
    flight: 'Flight',
    travelClass: 'Cabin',
    oftenDelayed: 'Often delayed by more than 30 minutes',
    routeMap: 'Route view',
    schematicRoute: 'A schematic is used because one or more airports are outside the local map catalogue.',
    checkedAt: 'Search returned',
    providerAsOf: 'Provider data from',
    cachedResult: 'RunIPS cache',
    sourceNotice:
      'Prices and availability are indexed search results, not a quote or reservation. They can change at any time; verify the selected flights before payment.',
    googleTitle: 'Check current availability',
    googleBody: 'Open the provider’s matching Google Flights search to refresh prices and continue to booking options.',
    googleAction: 'Open in Google Flights',
    matrixTitle: 'Advanced fare construction',
    matrixBody:
      'Open a one-way ITA Matrix search with this flight sequence. Matrix can expose fare rules and fare details, but it does not sell tickets.',
    routingCode: 'Exact ITA routing code',
    copyRouting: 'Copy code',
    copiedRouting: 'Copied',
    matrixAction: 'Open ITA Matrix',
    matrixFallback: 'If Matrix does not retain the restriction, open Advanced controls and paste the routing code.',
    noResultsTitle: 'No priced itineraries were returned',
    noResultsBody: 'Try the other arrival airport, another date, or open Google Flights for a broader search.',
    searchFailed: 'The live search could not be completed.',
    errorRate: 'The search limit for this connection has been reached. Please wait and try again.',
    errorDaily: 'Today’s shared live-search allowance has been reached. Google Flights and ITA Matrix are still available.',
    errorProvider: 'The flight provider is temporarily unavailable. Please try again shortly.',
    errorInvalid: 'Check the airport codes and departure date, then try again.',
    retry: 'Try again',
    documentTitle: 'Transit document screen',
    documentDescription:
      'A route-aware prompt for airside transit, self-transfer, baggage collection and entry into Japan.',
    noConnection: 'This itinerary is non-stop, so there is no transfer point to screen.',
    passportMissing: 'Add the passport-issuing country before relying on the transfer summary.',
    passengerProfile: 'Passenger profile',
    passport: 'Passport',
    booking: 'Booking',
    baggage: 'Baggage',
    transitAt: 'Transfer at',
    lowFriction: 'Lower-friction transfer',
    verify: 'Verify before booking',
    landside: 'Likely landside transfer',
    japanEntry: 'Entry into Japan',
    lowFrictionBody:
      'The itinerary is treated as one protected booking and the selected baggage plan does not require collection. Passport-specific airside rules still need confirmation.',
    verifyBody:
      'The ticket or baggage arrangement is not confirmed. Ask the operating airlines whether all boarding passes and baggage are issued through to the final destination.',
    landsideBody:
      'Separate tickets or baggage collection can require immigration clearance. Check entry or transit authorisation for this country using the traveller’s passport.',
    japanEntryBody:
      'This is the first airport in Japan before a domestic sector. Immigration and customs clearance take place here; allow enough connection time.',
    shortConnection: 'The connection may be too short for the selected transfer conditions.',
    overnightConnection: 'This connection is marked as overnight.',
    checkListTitle: 'Confirm before payment',
    checkTicket: 'Are all sectors on the same booking and protected after a delay?',
    checkBaggage: 'Will the airline tag checked baggage to the final airport?',
    checkAirside: 'Can the passenger remain airside and obtain every boarding pass?',
    checkPassport: 'What do official rules say for this passport and transit country?',
    twTransitPilot: 'Not covered by the transit scheme',
    twTransitPilotBody:
      'Transit through Taiwan on a Chinese passport falls within the pilot scheme only when the flight into Taoyuan departs directly from Chongqing (CKG), Kunming (KMG) or Nanchang (KHN). An itinerary that leaves China from somewhere else first — CKG–CAN–TPE, for instance — is outside the scheme, because the departure from China happens at Guangzhou. It is normally refused at check-in, before the airport. Choose a different transit point.',
    officialTitle: 'Check the official visa and entry rules',
    officialBody:
      'The IATA Travel Centre is the public interface to Timatic, the database airlines use to verify traveller documents. RunIPS does not determine visa requirements; rely on its results and on the relevant embassy.',
    officialFillTitle: 'Enter these there',
    officialFillNationality: 'Nationality',
    officialFillDestination: 'Destination',
    officialFillTransit: 'Transit',
    officialAction: 'Open the IATA Travel Centre',
    disclaimer:
      'This is a screening aid, not immigration advice. Confirm with the operating airline and the relevant official border authority before travel.',
    privateTitle: 'Minimal data by design',
    privateBody:
      'RunIPS sends only the route and date to its flight-search provider. Passport, ticket and baggage answers are not sent with the flight query or attached to an account.',
    privacyLink: 'Read the Travel Guide privacy details',
    futureTitle: 'Airport to campus transport',
    futureBadge: 'Coming later',
    futureBody:
      'The next stage will connect FUK and KKJ arrivals to the IPS campus and nearby housing. This release stops at the airport.',
    unknown: 'Not provided',
  },
  zh: {
    eyebrow: '飞往 IPS 的航空旅行',
    title: '规划一条抵达福冈的航线。',
    introduction: '搜索当日飞往 FUK 或 KKJ 的真实航班，按直飞与转机机场组合比较，再查看最低价行程的每一个航段。',
    flightsStage: '实时航班搜索',
    documentsStage: '转机证件筛查',
    localStage: '机场到学校 · 稍后上线',
    formTitle: '搜索航空行程',
    formDescription: '单程经济舱结果会按直飞或有序转机机场组合归类。',
    originLabel: '出发机场',
    originPlaceholder: '例如 长沙 或 CSX',
    originHelp: '输入城市名或机场代码，再从候选中选择。',
    invalidOrigin: '请从候选中选择出发机场，或直接输入三位代码；且不能与目的地相同。',
    destinationLabel: '抵达机场',
    fukOption: 'FUK · 福冈',
    kkjOption: 'KKJ · 北九州',
    dateLabel: '出发日期',
    dateHelp: '每次搜索一个具体日期。',
    invalidDate: '请选择今天起一年内的日期。',
    passportLabel: '护照签发国',
    passportPlaceholder: '例如 China',
    passportHelp: '只在当前浏览器内用于转机筛查。',
    ticketLabel: '出票方式',
    ticketSingle: '同一张受保护的联程票',
    ticketSeparate: '分开出票 / 自行转机',
    ticketUnknown: '暂不确定',
    baggageLabel: '行李安排',
    baggageThrough: '直挂至最终机场',
    baggageCollect: '中途提取并重新托运',
    baggageCabin: '只有随身行李',
    baggageUnknown: '暂不确定',
    searchAction: '搜索航班',
    searching: '正在搜索实时航班…',
    studentStatus: '默认旅客持有日本留学在留资格；证件筛查只针对抵达日本前的转机点。',
    searchDisclosure: '出发地、目的地与日期会经 RunIPS 发送给 SerpApi；护照、出票与行李答案只留在浏览器内。',
    initialTitle: '路线选择会显示在这里',
    initialBody: '选择机场与日期后比较直飞及转机行程；页面不再展示任何样例航班。',
    routeComparison: '路线选择',
    comparisonDescription: '每张卡片代表该转机组合中返回的最低价行程。',
    routesFound: (count: number) => `${count} 种路线组合`,
    offersFound: (count: number) => `共返回 ${count} 个行程`,
    direct: '直飞',
    via: (codes: string) => `经 ${codes}`,
    from: '最低',
    alternativeCount: (count: number) => `该组合有 ${count} 个选择`,
    itinerary: '该组合中的最低价行程',
    totalJourney: '总行程',
    connection: '次转机',
    connections: '次转机',
    overnight: '过夜',
    operatedBy: '航司',
    operatingCarrier: '实际承运',
    aircraft: '机型',
    flight: '航班',
    travelClass: '舱等',
    oftenDelayed: '经常延误 30 分钟以上',
    routeMap: '航线视图',
    schematicRoute: '部分机场不在本地地图目录中，因此这里使用准确的线性路线图。',
    checkedAt: '搜索返回时间',
    providerAsOf: '数据服务时间',
    cachedResult: 'RunIPS 缓存',
    sourceNotice: '票价与余位来自索引搜索结果，并非报价或预订；信息可能随时变化，请在付款前核对所选航班。',
    googleTitle: '查询当前余位',
    googleBody: '打开数据服务返回的对应 Google Flights 搜索，刷新票价并查看购票渠道。',
    googleAction: '在 Google Flights 中打开',
    matrixTitle: '高级票价组合',
    matrixBody: '按当前航班顺序打开 ITA Matrix 单程搜索，可查看 fare rules 与 fare details；Matrix 本身不售票。',
    routingCode: '精确 ITA routing code',
    copyRouting: '复制代码',
    copiedRouting: '已复制',
    matrixAction: '打开 ITA Matrix',
    matrixFallback: '如果 Matrix 没有保留限制，请打开 Advanced controls 并粘贴 routing code。',
    noResultsTitle: '没有返回带价格的行程',
    noResultsBody: '可改查另一个抵达机场或其他日期，也可以前往 Google Flights 扩大搜索。',
    searchFailed: '实时搜索未能完成。',
    errorRate: '当前连接的搜索次数已达上限，请稍后再试。',
    errorDaily: '今天的共享实时搜索额度已用完；仍可使用 Google Flights 与 ITA Matrix。',
    errorProvider: '航班数据服务暂时不可用，请稍后重试。',
    errorInvalid: '请检查机场代码与出发日期后重试。',
    retry: '重试',
    documentTitle: '转机证件筛查',
    documentDescription: '根据路线区分空侧转机、自行转机、提取行李与入境日本。',
    noConnection: '这个行程为不经停直飞，没有需要筛查的转机点。',
    passportMissing: '请先填写护照签发国，再参考转机结论。',
    passengerProfile: '旅客条件',
    passport: '护照',
    booking: '出票',
    baggage: '行李',
    transitAt: '转机地点',
    lowFriction: '较低阻力的转机',
    verify: '订票前需要确认',
    landside: '很可能需要进入陆侧',
    japanEntry: '在此入境日本',
    lowFrictionBody: '当前选择按同一张受保护的联程票处理，且无需中途提取行李；仍需按护照确认该国的空侧转机规则。',
    verifyBody: '出票或行李安排尚未确定。请向实际承运航司确认能否一次取得全部登机牌，以及行李能否直挂。',
    landsideBody: '分开出票或中途提取行李可能要求办理入境手续，请按旅客护照确认该国的入境或过境许可。',
    japanEntryBody: '这里是衔接日本国内航班前的首个日本机场，需要办理入境与海关手续，并预留足够转机时间。',
    shortConnection: '以当前转机方式来看，衔接时间可能过短。',
    overnightConnection: '该次转机被标记为过夜。',
    checkListTitle: '付款前逐项确认',
    checkTicket: '所有航段是否在同一订单内，延误后是否受保护？',
    checkBaggage: '航司是否会把托运行李标记至最终机场？',
    checkAirside: '能否留在空侧，并取得后续全部登机牌？',
    checkPassport: '官方规则对这本护照及该转机国家如何规定？',
    twTransitPilot: '不在中转试点范围内',
    twTransitPilotBody:
      '持中国因私护照经台湾中转，仅当由重庆（CKG）、昆明（KMG）、南昌（KHN）直飞抵达桃园时才在试点范围内。若先在其他城市出境再转（例如 CKG–CAN–TPE，出境发生在广州），则不属于试点，通常在值机环节即被拒绝，不会等到机场。请改选其他中转地。',
    officialTitle: '查官方签证与入境要求',
    officialBody:
      'IATA Travel Centre 是 Timatic 数据库的公开查询入口，各航司据此核验旅客证件。RunIPS 不判定签证要求，请以其查询结果及相关使领馆信息为准。',
    officialFillTitle: '在那边填这些',
    officialFillNationality: '护照签发国',
    officialFillDestination: '目的地',
    officialFillTransit: '中转',
    officialAction: '打开 IATA Travel Centre',
    disclaimer: '这只是筛查工具，不是移民建议。出发前请向实际承运航司与相关官方边境机构确认。',
    privateTitle: '数据最小化设计',
    privateBody: 'RunIPS 只把路线与日期发送给航班搜索服务；护照、出票与行李答案不会随查询发送，也不会关联到账号。',
    privacyLink: '查看旅行指南隐私说明',
    futureTitle: '机场到学校交通',
    futureBadge: '稍后上线',
    futureBody: '下一阶段会把 FUK 与 KKJ 的抵达航班接到 IPS 校区和附近住处；当前版本止于机场。',
    unknown: '未提供',
  },
};
