import { Lang } from '@/i18n/translations';

const communityCopy = {
  en: {
    eyebrow: 'RUNIPS / COMMUNITY',
    title: 'Community',
    intro: 'Create once, find it later. Durable topics about studying, research and daily life at Waseda IPS.',
    nav: {
      browse: 'Browse',
      ask: 'New topic',
      notifications: 'Notifications',
    },
    actions: {
      createTopic: 'New topic',
      retry: 'Try again',
      back: 'Back to Community',
      signIn: 'Sign in to continue',
      report: 'Report',
      reporting: 'Reporting…',
      markSolution: 'Accept reply',
      markingSolution: 'Saving…',
      follow: 'Follow',
      following: 'Following',
      updatingFollow: 'Saving…',
    },
    index: {
      searchLabel: 'Search Community',
      searchPlaceholder: 'Search Community topics',
      categoryLabel: 'Category',
      allCategories: 'All categories',
      filters: {
        latest: 'Latest',
        open: 'Open',
        resolved: 'Resolved',
      },
      reply: 'reply',
      replies: 'replies',
      lastActive: 'Last active {date}',
      searching: 'Searching all Community topics…',
      searchUnavailable: 'Full Community search is temporarily unavailable; showing matches from the latest topics.',
      emptyTitle: 'No topics yet',
      emptyDescription: 'Start the first durable conversation for the IPS community.',
      filteredEmptyTitle: 'No matching topics',
      filteredEmptyDescription: 'Try a broader search, another category or a different filter.',
    },
    status: {
      open: 'Open',
      resolved: 'Resolved',
      duplicate: 'Duplicate',
      closed: 'Closed',
      locked: 'Locked',
      hidden: 'Hidden',
      deleted: 'Removed',
    },
    state: {
      loading: 'Loading Community…',
      loadFailedTitle: 'Community could not be loaded',
      loadFailedDescription: 'Please check your connection and try again.',
      unavailableTitle: 'Community is not available yet',
      unavailableDescription: 'The Community database module has not been installed on this environment.',
    },
    newTopic: {
      eyebrow: 'CREATE A TOPIC',
      title: 'Start a useful topic',
      intro: 'Use a clear title so people looking for the same information can find this page later.',
      signInTitle: 'Sign in before posting',
      signInDescription: 'Anyone can read Community. A RunIPS account is required to create topics and replies, which helps limit spam.',
      titleLabel: 'Title',
      titlePlaceholder: 'For example: When should I start looking for housing?',
      titleHint: 'Keep it specific. Similar topics will appear as you type.',
      bodyLabel: 'Details (optional)',
      bodyPlaceholder: 'Add context, what you have already checked, or what you would like the community to contribute.',
      bodyHint: 'Do not include names, student numbers, contact details or other unnecessary personal information.',
      categoryLabel: 'Category',
      categoryPlaceholder: 'Choose a category',
      similarTitle: 'Check these existing topics first',
      similarLoading: 'Looking for similar topics…',
      similarUnavailable: 'Automatic duplicate checking is temporarily unavailable. You can still review Community search before posting.',
      similarResolved: 'This topic already has an accepted reply.',
      similarDuplicate: 'This topic points to an earlier canonical topic.',
      reviewedSimilar: 'I checked these topics and they do not cover what I want to post.',
      agreement: 'I will keep this topic relevant and respectful, avoid personal data and follow the Community rules.',
      followHint: 'Publishing automatically follows this topic for in-app reply notifications. You can unfollow it from the topic page at any time.',
      legalPrefix: 'Public posts can be read by anyone. Read the',
      privacy: 'Privacy Notice',
      terms: 'Terms',
      publish: 'Publish topic',
      publishing: 'Publishing…',
      validationTitle: 'Enter a title between 1 and 160 characters.',
      validationBody: 'Details cannot exceed 10,000 characters.',
      validationCategory: 'Choose a category.',
      validationSimilarLoading: 'Wait for the similar-topic check to finish.',
      validationSimilar: 'Review the similar topics before publishing.',
      validationAgreement: 'Confirm the privacy and Community rules before publishing.',
      publishFailed: 'The topic could not be published. Please try again.',
      categoriesEmpty: 'No Community categories have been configured yet.',
    },
    topic: {
      invalidTitle: 'Invalid topic link',
      invalidDescription: 'This Community link does not contain a valid topic ID.',
      notFoundTitle: 'Topic not found',
      notFoundDescription: 'It may have been removed or the link may be incorrect.',
      byline: '{author} · {date}',
      noDetails: 'No further details were provided.',
      duplicatePrefix: 'This topic was marked as a duplicate of',
      canonicalTopic: 'the canonical topic',
      acceptedAnswer: 'Accepted reply',
      repliesTitle: 'Replies',
      noRepliesTitle: 'No replies yet',
      noRepliesDescription: 'If you can help, add the first reply.',
      acceptedOnly: 'The accepted reply is shown above.',
      deletedReply: 'This reply was removed when its author deleted their account.',
      author: 'Topic author',
      edited: 'Edited',
      replyTitle: 'Add a reply',
      replyPlaceholder: 'Write a clear and constructive reply.',
      replyHint: 'Plain text only. Do not share another person’s private information. Posting automatically follows this topic for in-app notifications; you can unfollow at any time.',
      replySubmit: 'Post reply',
      replying: 'Posting…',
      replyValidation: 'A reply must contain between 1 and 10,000 characters.',
      replyFailed: 'The reply could not be posted. Please try again.',
      replyClosed: 'Replies are closed for this topic.',
      signInToReply: 'Sign in to reply',
      reportConfirm: 'Report this content for review under the Community guidelines?',
      reportSuccess: 'The report was submitted for moderator review.',
      reportFailed: 'The report could not be submitted. Please try again.',
      solutionSuccess: 'The accepted reply has been updated.',
      solutionFailed: 'The accepted reply could not be updated. Please try again.',
      followSuccess: 'You will receive notifications about new replies to this topic.',
      unfollowSuccess: 'Notifications for this topic have been turned off.',
      followFailed: 'The notification preference could not be updated. Please try again.',
      moderationTitle: 'Moderator tools',
      moderationQueue: 'Open report queue',
      moderationDuplicateLabel: 'Canonical topic ID',
      moderationDuplicatePlaceholder: 'For example: 123',
      moderationDuplicate: 'Mark duplicate',
      moderationLock: 'Lock',
      moderationClose: 'Close',
      moderationReopen: 'Reopen',
      moderationConfirm: 'Apply this moderation action to the topic?',
      moderationInvalidDuplicate: 'Enter a different, valid canonical topic ID.',
      moderationSuccess: 'The topic moderation status has been updated.',
      moderationFailed: 'The moderation action failed. Please check the target and try again.',
      replyHidden: 'Hidden from public view',
      hideReply: 'Hide reply',
      restoreReply: 'Restore reply',
      replyModerationConfirm: 'Apply this moderation action to the reply?',
      replyModerationSuccess: 'The reply moderation status has been updated.',
      replyModerationFailed: 'The reply moderation action failed.',
    },
    notifications: {
      eyebrow: 'YOUR UPDATES',
      title: 'Notifications',
      intro: 'Replies and status changes for your Community topics appear here.',
      signInTitle: 'Sign in to see notifications',
      signInDescription: 'Notifications are private to your RunIPS account.',
      unread: 'Unread',
      read: 'Read',
      markRead: 'Mark as read',
      markingRead: 'Saving…',
      emptyTitle: 'No notifications',
      emptyDescription: 'New replies and accepted-reply updates will appear here.',
      kinds: {
        reply: 'New reply',
        solution: 'Accepted reply update',
        moderation: 'Moderation update',
        other: 'Community update',
      },
      markFailed: 'The notification could not be updated.',
    },
    moderation: {
      eyebrow: 'MODERATOR / REPORTS',
      title: 'Open reports',
      intro: 'Review reported Community content. Hiding content also resolves its report in the same operation.',
      signInTitle: 'Sign in to continue',
      signInDescription: 'The moderation queue is restricted to authorised Community moderators.',
      deniedTitle: 'Moderator access required',
      deniedDescription: 'This account does not have permission to view Community reports.',
      emptyTitle: 'No open reports',
      emptyDescription: 'There is no reported content waiting for review.',
      topic: 'Topic report',
      reply: 'Reply report',
      reported: 'Reported {date}',
      reason: 'Report reason',
      content: 'Reported content',
      hide: 'Hide content and resolve',
      dismiss: 'Dismiss report',
      working: 'Saving…',
      hideConfirm: 'Hide this content from public view and resolve the report?',
      dismissConfirm: 'Dismiss this report without changing the content?',
      actionFailed: 'The report could not be updated. Please try again.',
    },
  },
  zh: {
    eyebrow: 'RUNIPS / 交流中心',
    title: '交流中心',
    intro: '内容只需认真整理一次，之后每个人都能找到。这里可以交流早稻田 IPS 的学习、研究与日常生活。',
    nav: {
      browse: '浏览',
      ask: '新建主题',
      notifications: '通知',
    },
    actions: {
      createTopic: '新建主题',
      retry: '重试',
      back: '返回交流中心',
      signIn: '登录后继续',
      report: '举报',
      reporting: '提交中…',
      markSolution: '采纳回复',
      markingSolution: '保存中…',
      follow: '关注',
      following: '已关注',
      updatingFollow: '保存中…',
    },
    index: {
      searchLabel: '搜索交流中心',
      searchPlaceholder: '搜索交流中心主题',
      categoryLabel: '分类',
      allCategories: '全部分类',
      filters: {
        latest: '最新',
        open: '开放',
        resolved: '已解决',
      },
      reply: '条回复',
      replies: '条回复',
      lastActive: '最后活动于 {date}',
      searching: '正在搜索全部交流中心主题…',
      searchUnavailable: '完整搜索暂时不可用，当前仅显示最近主题中的匹配结果。',
      emptyTitle: '还没有主题',
      emptyDescription: '为 IPS 社区发布第一个可以长期查找的主题。',
      filteredEmptyTitle: '没有匹配的主题',
      filteredEmptyDescription: '可以减少搜索词、切换分类或选择其他筛选条件。',
    },
    status: {
      open: '开放',
      resolved: '已解决',
      duplicate: '重复',
      closed: '已关闭',
      locked: '已锁定',
      hidden: '已隐藏',
      deleted: '已移除',
    },
    state: {
      loading: '正在加载交流中心…',
      loadFailedTitle: '交流中心加载失败',
      loadFailedDescription: '请检查网络连接后重试。',
      unavailableTitle: '交流中心暂未开放',
      unavailableDescription: '当前环境还没有安装交流中心数据库模块。',
    },
    newTopic: {
      eyebrow: '新建主题',
      title: '新建一个有长期价值的主题',
      intro: '请使用清楚、具体的标题，让之后查找相同信息的人能够找到这里。',
      signInTitle: '登录后发帖',
      signInDescription: '所有人都可以阅读交流中心。为减少垃圾内容，发帖和回复需要登录 RunIPS 账号。',
      titleLabel: '标题',
      titlePlaceholder: '例如：应该从什么时候开始找房？',
      titleHint: '请尽量具体；输入时会自动显示相似主题。',
      bodyLabel: '补充说明（可选）',
      bodyPlaceholder: '可以补充背景、已经查过的资料，或希望社区提供哪些信息。',
      bodyHint: '请勿填写姓名、学号、联系方式或其他不必要的个人信息。',
      categoryLabel: '分类',
      categoryPlaceholder: '选择分类',
      similarTitle: '请先查看这些已有主题',
      similarLoading: '正在查找相似主题…',
      similarUnavailable: '自动查重暂时不可用。发帖前仍建议先搜索交流中心。',
      similarResolved: '这个主题已经有已采纳回复。',
      similarDuplicate: '这个主题已经指向更早的主主题。',
      reviewedSimilar: '我已查看这些主题，它们没有涵盖我准备发布的内容。',
      agreement: '我会保持内容相关、尊重他人、不公开个人信息，并遵守社区规则。',
      followHint: '发布后会自动关注这个主题并接收站内回复通知；你可以随时在主题页面取消关注。',
      legalPrefix: '公开内容可被任何人查看。提交前请阅读',
      privacy: '隐私保护说明',
      terms: '条款与条件',
      publish: '发布主题',
      publishing: '发布中…',
      validationTitle: '标题需要包含 1–160 个字符。',
      validationBody: '补充说明不能超过 10,000 个字符。',
      validationCategory: '请选择一个分类。',
      validationSimilarLoading: '请等待相似主题检查完成。',
      validationSimilar: '发布前请先确认已经查看相似主题。',
      validationAgreement: '发布前请确认隐私与社区规则。',
      publishFailed: '主题发布失败，请稍后重试。',
      categoriesEmpty: '目前还没有配置交流中心分类。',
    },
    topic: {
      invalidTitle: '主题链接无效',
      invalidDescription: '这个交流中心链接没有包含有效的主题编号。',
      notFoundTitle: '没有找到主题',
      notFoundDescription: '它可能已被移除，或者链接有误。',
      byline: '{author} · {date}',
      noDetails: '发帖者没有填写更多说明。',
      duplicatePrefix: '这个主题已被标记为重复主题，原始主题为',
      canonicalTopic: '主主题',
      acceptedAnswer: '已采纳回复',
      repliesTitle: '回复',
      noRepliesTitle: '还没有回复',
      noRepliesDescription: '如果你有相关信息，可以留下第一条回复。',
      acceptedOnly: '已采纳回复显示在上方。',
      deletedReply: '这条回复已在作者删除账号时移除。',
      author: '主题作者',
      edited: '已编辑',
      replyTitle: '添加回复',
      replyPlaceholder: '写下清楚、具体且有建设性的回复。',
      replyHint: '仅支持纯文本，请勿公开他人的隐私信息。发布回复后会自动关注此主题并接收站内通知，可随时取消关注。',
      replySubmit: '发布回复',
      replying: '发布中…',
      replyValidation: '回复需要包含 1–10,000 个字符。',
      replyFailed: '回复发布失败，请稍后重试。',
      replyClosed: '这个主题目前不接受新回复。',
      signInToReply: '登录后回复',
      reportConfirm: '确认按照社区规则举报这条内容并交由管理员复核？',
      reportSuccess: '举报已提交，管理员会进行复核。',
      reportFailed: '举报提交失败，请稍后重试。',
      solutionSuccess: '已更新采纳回复。',
      solutionFailed: '无法更新已采纳回复，请稍后重试。',
      followSuccess: '有新回复时，你会在通知页面收到提醒。',
      unfollowSuccess: '已关闭这个主题的通知。',
      followFailed: '通知设置更新失败，请稍后重试。',
      moderationTitle: '管理员工具',
      moderationQueue: '查看待处理举报',
      moderationDuplicateLabel: '主主题编号',
      moderationDuplicatePlaceholder: '例如：123',
      moderationDuplicate: '标记为重复',
      moderationLock: '锁定',
      moderationClose: '关闭',
      moderationReopen: '重新开放',
      moderationConfirm: '确认对这个主题执行该管理操作？',
      moderationInvalidDuplicate: '请输入另一个有效的主主题编号。',
      moderationSuccess: '主题管理状态已更新。',
      moderationFailed: '管理操作失败，请检查目标编号后重试。',
      replyHidden: '已从公开页面隐藏',
      hideReply: '隐藏回复',
      restoreReply: '恢复回复',
      replyModerationConfirm: '确认对这条回复执行该管理操作？',
      replyModerationSuccess: '回复管理状态已更新。',
      replyModerationFailed: '回复管理操作失败。',
    },
    notifications: {
      eyebrow: '你的动态',
      title: '通知',
      intro: '与你的交流中心主题相关的回复和状态变化会显示在这里。',
      signInTitle: '登录后查看通知',
      signInDescription: '通知仅对你的 RunIPS 账号可见。',
      unread: '未读',
      read: '已读',
      markRead: '标为已读',
      markingRead: '保存中…',
      emptyTitle: '暂无通知',
      emptyDescription: '新的回复和采纳回复更新会显示在这里。',
      kinds: {
        reply: '新回复',
        solution: '采纳回复更新',
        moderation: '管理状态更新',
        other: '社区动态',
      },
      markFailed: '通知状态更新失败。',
    },
    moderation: {
      eyebrow: '管理员 / 举报',
      title: '待处理举报',
      intro: '在这里复核交流中心的举报。隐藏内容时会在同一个操作中将举报标记为已解决。',
      signInTitle: '登录后继续',
      signInDescription: '举报处理页面仅限获得授权的交流中心管理员。',
      deniedTitle: '需要管理员权限',
      deniedDescription: '当前账号没有查看交流中心举报的权限。',
      emptyTitle: '没有待处理举报',
      emptyDescription: '目前没有等待复核的举报内容。',
      topic: '主题举报',
      reply: '回复举报',
      reported: '举报于 {date}',
      reason: '举报原因',
      content: '被举报内容',
      hide: '隐藏内容并解决',
      dismiss: '驳回举报',
      working: '保存中…',
      hideConfirm: '确认隐藏这条内容，并将举报标记为已解决？',
      dismissConfirm: '确认在不修改内容的情况下驳回这条举报？',
      actionFailed: '举报状态更新失败，请稍后重试。',
    },
  },
} as const;

export function getCommunityCopy(lang: Lang) {
  return communityCopy[lang];
}

export function interpolateCommunityCopy(
  value: string,
  params: Record<string, string | number>,
): string {
  return Object.entries(params).reduce(
    (text, [key, replacement]) => text.replace(`{${key}}`, String(replacement)),
    value,
  );
}
