-- RunIPS database baseline for a fresh self-hosted Supabase/PostgreSQL instance.
-- IDs are explicit because they are part of the statically generated professor URLs.

create table if not exists public.professors (
  id bigint generated by default as identity primary key,
  name text not null,
  lab text,
  division text not null check (division in ('情報アーキテクチャ', '生産システム', '集積システム')),
  scholar_citations integer check (scholar_citations is null or scholar_citations >= 0),
  search_count bigint not null default 0 check (search_count >= 0),
  click_count bigint not null default 0 check (click_count >= 0),
  citations_updated_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.professors enable row level security;

drop policy if exists "professors are publicly readable" on public.professors;
create policy "professors are publicly readable"
on public.professors for select to anon, authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant select on public.professors to anon, authenticated;

create or replace function public.increment_clicks(p_professor_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_count bigint;
begin
  update public.professors
  set click_count = click_count + 1
  where id = p_professor_id
  returning click_count into next_count;

  return next_count;
end;
$$;

revoke all on function public.increment_clicks(bigint) from public;
grant execute on function public.increment_clicks(bigint) to anon, authenticated;

insert into public.professors (id, name, lab, division) values
  (1, '藤村 茂', 'スマートインダストリー研究室', '情報アーキテクチャ'),
  (2, '古月 敬之', 'ニューロコンピューティング研究室', '情報アーキテクチャ'),
  (3, '岩井原 瑞穂', 'データ工学研究室', '情報アーキテクチャ'),
  (4, '鎌田 清一郎', 'イメージメディア研究室', '情報アーキテクチャ'),
  (5, '亀岡 遵', 'バイオ情報センシング研究室', '情報アーキテクチャ'),
  (6, 'ルパージュ・イヴ', '用例翻訳・言語処理研究室', '情報アーキテクチャ'),
  (7, '松丸 隆文', 'バイオロボティクス&ヒューマン・メカトロニクス研究室', '情報アーキテクチャ'),
  (8, '吉江 修', 'コミュニティ・コンピューティング研究室', '情報アーキテクチャ'),
  (9, '伍 軍', 'ネットワークインテリジェンスとセキュリティ研究室', '情報アーキテクチャ'),
  (10, '家入 祐也', 'ヒューマニティ中心インタラクション研究室', '情報アーキテクチャ'),
  (11, '荒川 雅生', '設計工学システム研究室', '生産システム'),
  (12, '橋本 健二', '移動ロボティクス・プラットフォーム研究室', '生産システム'),
  (13, '馬渡 和真', 'マイクロナノ流体デバイス研究室', '生産システム'),
  (14, '三宅 丈雄', 'バイオイオントロニクス研究室', '生産システム'),
  (15, '田中 英一郎', '機械システム設計研究室', '生産システム'),
  (16, '立野 繁之', '生産プロセス工学研究室', '生産システム'),
  (17, '植田 研二', '知能半導体工学研究室', '生産システム'),
  (18, '志村 考功', '半導体デバイス材料工学研究室', '生産システム'),
  (19, '高橋 淳子', '生体医工学研究室', '生産システム'),
  (20, '山口 恭平', 'パワートレインシステム研究室', '生産システム'),
  (22, '池橋 民雄', 'マイクロ電気機械システム研究室', '集積システム'),
  (23, '池永 剛', '画像情報システム研究室', '集積システム'),
  (24, '硴塚 孝明', '発光システム研究室', '集積システム'),
  (25, '木村 晋二', '高位検証技術研究室', '集積システム'),
  (26, '牧野 昭二', '知的音響システム研究室', '集積システム'),
  (27, '髙畑 清人', '光電子集積システム研究室', '集積システム'),
  (28, '丹沢 徹', 'グリーン集積システム研究室', '集積システム'),
  (29, '山﨑 慎太郎', '集積システム最適化研究室', '集積システム'),
  (30, '吉増 敏彦', '無線通信回路技術研究室', '集積システム'),
  (31, '芹田 和則', 'テラヘルツ集積システム研究室', '集積システム'),
  (32, '董世杰', 'Hippo8!415', '情報アーキテクチャ')
on conflict (id) do update set
  name = excluded.name,
  lab = excluded.lab,
  division = excluded.division;

select setval(
  pg_get_serial_sequence('public.professors', 'id'),
  (select max(id) from public.professors),
  true
);
