-- Identity fields are chosen once, then fixed.
--
-- Two changes to `update_my_account_profile`:
--
--   1. `p_username` is gone. Usernames were already generated by the column
--      default (`member_` plus a zero-padded sequence value), but the RPC let a
--      caller overwrite that, and overwrite it again on every later save. The
--      handle a person is cited by across topics, replies and reviews should
--      not be reassignable, so it is no longer an input at all.
--
--   2. `display_name` may be set while `profile_completed_at` is null — that is
--      registration — and is fixed afterwards. Sending the value it already has
--      is still accepted so that changing only the avatar colour keeps working;
--      sending a different one raises.
--
-- `avatar_colour` stays freely editable: it is decoration, not identity.
--
-- The old three-argument function is dropped rather than replaced, because
-- changing the signature would otherwise leave both versions callable.

drop function if exists public.update_my_account_profile(text, text, text);

create or replace function public.update_my_account_profile(
  p_display_name text,
  p_avatar_colour text
)
returns table (
  username text,
  display_name text,
  avatar_colour text,
  waseda_verified boolean,
  profile_completed boolean,
  is_permanent boolean,
  has_google_identity boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_display_name text := btrim(coalesce(p_display_name, ''));
  normalised_avatar_colour text := lower(btrim(coalesce(p_avatar_colour, '')));
  existing_display_name text;
  already_completed boolean;
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  if not public.account_is_permanent(requesting_user) then
    raise exception using errcode = '42501', message = 'A permanent account is required';
  end if;

  if char_length(normalised_display_name) < 1
    or char_length(normalised_display_name) > 40
    or normalised_display_name ~ '[[:cntrl:]]' then
    raise exception using errcode = '22023', message = 'Display name must contain 1 to 40 visible characters';
  end if;

  if lower(normalised_display_name) in (
    'admin', 'administrator', 'moderator', 'runips', 'runips team',
    'runips support', 'waseda', 'waseda university', 'waseda official'
  ) then
    raise exception using errcode = '22023', message = 'This display name is reserved';
  end if;

  if normalised_avatar_colour not in (
    'violet', 'cyan', 'blue', 'emerald', 'amber', 'rose', 'slate', 'indigo'
  ) then
    raise exception using errcode = '22023', message = 'Invalid avatar colour';
  end if;

  -- Ensures a row exists so the username default fires exactly once.
  insert into public.account_profiles (user_id)
  values (requesting_user)
  on conflict (user_id) do nothing;

  select profile.display_name, profile.profile_completed_at is not null
  into existing_display_name, already_completed
  from public.account_profiles profile
  where profile.user_id = requesting_user;

  if already_completed and coalesce(existing_display_name, '') <> normalised_display_name then
    raise exception using
      errcode = '22023',
      message = 'The display name cannot be changed after registration';
  end if;

  update public.account_profiles profile
  set display_name = normalised_display_name,
      avatar_colour = normalised_avatar_colour,
      profile_completed_at = coalesce(profile.profile_completed_at, now())
  where profile.user_id = requesting_user;

  perform public.sync_account_waseda_verification(requesting_user);

  return query
  select
    profile.username,
    profile.display_name,
    profile.avatar_colour,
    profile.waseda_verified,
    true,
    true,
    exists (
      select 1
      from auth.identities identity_record
      where identity_record.user_id = requesting_user
        and identity_record.provider = 'google'
    ),
    profile.created_at
  from public.account_profiles profile
  where profile.user_id = requesting_user;
end;
$$;

revoke all on function public.update_my_account_profile(text, text) from public;
grant execute on function public.update_my_account_profile(text, text) to authenticated;
