-- Private feedback inbox. Visitors can submit through a narrow RPC, but no
-- public or authenticated browser role can read the inbox directly.

create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  reference_code uuid not null default gen_random_uuid() unique,
  user_id uuid default auth.uid() references auth.users(id) on delete set null,
  category text not null check (category in ('general', 'bug', 'privacy', 'content', 'other')),
  message text not null check (
    char_length(message) <= 4000
    and char_length(btrim(message)) >= 5
  ),
  reply_contact text check (
    reply_contact is null
    or (
      char_length(reply_contact) <= 320
      and char_length(btrim(reply_contact)) >= 3
    )
  ),
  page_url text check (page_url is null or char_length(page_url) <= 500),
  locale text not null default 'en' check (locale in ('zh', 'en', 'other')),
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists feedback_submissions_status_created_idx
  on public.feedback_submissions (status, created_at desc);

drop trigger if exists feedback_submissions_touch_updated_at on public.feedback_submissions;
create trigger feedback_submissions_touch_updated_at
before update on public.feedback_submissions
for each row execute function public.touch_professor_review_updated_at();

alter table public.feedback_submissions enable row level security;

revoke all on public.feedback_submissions from public, anon, authenticated;
revoke all on sequence public.feedback_submissions_id_seq from public, anon, authenticated;

create or replace function public.submit_feedback(
  p_category text,
  p_message text,
  p_reply_contact text default null,
  p_page_url text default null,
  p_locale text default 'en',
  p_website text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_category text := lower(btrim(coalesce(p_category, '')));
  normalized_message text := btrim(coalesce(p_message, ''));
  normalized_reply_contact text := nullif(btrim(coalesce(p_reply_contact, '')), '');
  normalized_page_url text := nullif(btrim(coalesce(p_page_url, '')), '');
  normalized_locale text := lower(btrim(coalesce(p_locale, '')));
  new_reference uuid;
begin
  -- Honeypot field: ordinary users never see or fill this value.
  if nullif(btrim(coalesce(p_website, '')), '') is not null then
    raise exception using errcode = '22023', message = 'Invalid feedback submission';
  end if;

  if normalized_category not in ('general', 'bug', 'privacy', 'content', 'other') then
    raise exception using errcode = '22023', message = 'Invalid feedback category';
  end if;

  if char_length(normalized_message) < 5 or char_length(normalized_message) > 4000 then
    raise exception using errcode = '22023', message = 'Feedback message must contain 5 to 4000 characters';
  end if;

  if normalized_reply_contact is not null
    and (char_length(normalized_reply_contact) < 3 or char_length(normalized_reply_contact) > 320) then
    raise exception using errcode = '22023', message = 'Invalid reply contact';
  end if;

  if normalized_page_url is not null and char_length(normalized_page_url) > 500 then
    raise exception using errcode = '22023', message = 'Related page is too long';
  end if;

  if normalized_locale not in ('zh', 'en') then
    normalized_locale := 'other';
  end if;

  insert into public.feedback_submissions (
    user_id,
    category,
    message,
    reply_contact,
    page_url,
    locale
  )
  values (
    auth.uid(),
    normalized_category,
    normalized_message,
    normalized_reply_contact,
    normalized_page_url,
    normalized_locale
  )
  returning reference_code into new_reference;

  return new_reference;
end;
$$;

revoke all on function public.submit_feedback(text, text, text, text, text, text) from public;
grant execute on function public.submit_feedback(text, text, text, text, text, text) to anon, authenticated;

comment on table public.feedback_submissions is
  'Private RunIPS feedback inbox. Browser roles can submit only through submit_feedback and cannot read rows.';
