-- RunIPS Community MVP: durable, searchable questions and discussions.
-- Browser roles read only sanitised views and write only through narrow RPCs.

create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

-- pg_trgm is relocatable. Keep a pre-enabled installation consistent with
-- Supabase's extension schema so the qualified function and opclass below are
-- valid on both fresh and previously prepared instances.
do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_extension extension
    join pg_catalog.pg_namespace namespace on namespace.oid = extension.extnamespace
    where extension.extname = 'pg_trgm'
      and namespace.nspname <> 'extensions'
  ) then
    alter extension pg_trgm set schema extensions;
  end if;
end;
$$;

create table public.community_categories (
  id smallint generated by default as identity primary key,
  slug text not null unique check (
    slug = lower(slug)
    and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    and char_length(slug) <= 64
  ),
  name_en text not null check (char_length(btrim(name_en)) between 1 and 80),
  name_zh text not null check (char_length(btrim(name_zh)) between 1 and 80),
  description_en text not null default '' check (char_length(description_en) <= 300),
  description_zh text not null default '' check (char_length(description_zh) <= 300),
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.community_categories (
  id,
  slug,
  name_en,
  name_zh,
  description_en,
  description_zh,
  sort_order
) values
  (1, 'admissions', 'Admissions', '入学申请', 'Applications, entry requirements and enrolment.', '申请、入学要求与注册。', 10),
  (2, 'academic-life', 'Academic life', '学术生活', 'Study, modules and academic administration.', '学习、课程与教务。', 20),
  (3, 'research-laboratories', 'Research & laboratories', '研究与实验室', 'Research, supervisors and laboratory life.', '研究、导师与实验室生活。', 30),
  (4, 'campus-services', 'Campus services', '校园服务', 'Facilities, systems and services at Waseda.', '早稻田的设施、系统与服务。', 40),
  (5, 'living-in-japan', 'Living in Japan', '日本生活', 'Housing, transport and everyday life.', '住宿、交通与日常生活。', 50),
  (6, 'visas-administration', 'Visas & administration', '签证与行政手续', 'Visas, residence status and official procedures.', '签证、在留资格与行政手续。', 60),
  (7, 'careers', 'Careers', '职业发展', 'Internships, job hunting and careers.', '实习、求职与职业发展。', 70),
  (8, 'other', 'Other', '其他', 'Questions and discussions that do not fit elsewhere.', '不属于其他分类的问题与讨论。', 80)
on conflict (id) do update set
  slug = excluded.slug,
  name_en = excluded.name_en,
  name_zh = excluded.name_zh,
  description_en = excluded.description_en,
  description_zh = excluded.description_zh,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.community_categories', 'id'),
  (select max(id) from public.community_categories),
  true
);

create table public.community_topics (
  id bigint generated by default as identity primary key,
  author_user_id uuid default auth.uid() references auth.users(id) on delete set null,
  kind text not null check (kind in ('question', 'discussion', 'guide')),
  category_id smallint not null references public.community_categories(id),
  title text not null check (
    char_length(btrim(title)) > 0
    and char_length(title) <= 160
  ),
  body text not null default '' check (char_length(body) <= 10000),
  status text not null default 'open' check (
    status in ('open', 'resolved', 'duplicate', 'closed', 'locked', 'hidden', 'deleted')
  ),
  accepted_reply_id bigint,
  duplicate_of_topic_id bigint references public.community_topics(id) on delete set null,
  source_type text not null default 'user' check (
    source_type in ('user', 'staff', 'wechat_archive')
  ),
  source_note text check (source_note is null or char_length(source_note) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  check (duplicate_of_topic_id is null or duplicate_of_topic_id <> id),
  check (
    (status = 'duplicate' and duplicate_of_topic_id is not null)
    or (status <> 'duplicate' and duplicate_of_topic_id is null)
  ),
  check (accepted_reply_id is null or kind = 'question')
);

create table public.community_replies (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  author_user_id uuid default auth.uid() references auth.users(id) on delete set null,
  body text not null,
  quote_reply_id bigint references public.community_replies(id) on delete set null,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  source_type text not null default 'user' check (
    source_type in ('user', 'staff', 'wechat_archive')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'deleted' and body = '')
    or (
      status <> 'deleted'
      and char_length(btrim(body)) > 0
      and char_length(body) <= 10000
    )
  )
);

alter table public.community_topics
  add constraint community_topics_accepted_reply_fk
  foreign key (accepted_reply_id)
  references public.community_replies(id)
  on delete set null
  deferrable initially immediate;

create table public.community_tags (
  id bigint generated by default as identity primary key,
  slug text not null unique check (
    char_length(btrim(slug)) between 1 and 40
    and slug = lower(slug)
  ),
  name text not null check (char_length(btrim(name)) between 1 and 40),
  created_at timestamptz not null default now()
);

create table public.community_topic_tags (
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  tag_id bigint not null references public.community_tags(id) on delete cascade,
  primary key (topic_id, tag_id)
);

create table public.community_topic_entity_links (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  entity_type text not null check (
    entity_type in ('professor', 'laboratory', 'course', 'travel_guide', 'other')
  ),
  entity_key text not null check (char_length(btrim(entity_key)) between 1 and 160),
  label text check (label is null or char_length(btrim(label)) between 1 and 160),
  url text check (url is null or char_length(url) <= 500),
  created_at timestamptz not null default now(),
  unique (topic_id, entity_type, entity_key)
);

create table public.community_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  topic_id bigint references public.community_topics(id) on delete cascade,
  reply_id bigint references public.community_replies(id) on delete cascade,
  reason text not null check (char_length(btrim(reason)) between 2 and 1000),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((topic_id is not null)::integer + (reply_id is not null)::integer = 1)
);

create unique index community_reports_topic_reporter_uidx
  on public.community_reports (reporter_user_id, topic_id)
  where topic_id is not null;

create unique index community_reports_reply_reporter_uidx
  on public.community_reports (reporter_user_id, reply_id)
  where reply_id is not null;

create table public.community_subscriptions (
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (topic_id, user_id)
);

create table public.community_notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('reply', 'solution', 'topic_moderated')),
  topic_id bigint not null references public.community_topics(id) on delete cascade,
  reply_id bigint references public.community_replies(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table public.community_moderators (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'moderator' check (role in ('moderator', 'owner')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index community_topics_category_activity_idx
  on public.community_topics (category_id, last_activity_at desc)
  where status <> 'hidden';

create index community_topics_status_activity_idx
  on public.community_topics (status, last_activity_at desc);

create index community_topics_title_trgm_idx
  on public.community_topics
  using gin ((lower(title)) extensions.gin_trgm_ops);

create index community_replies_topic_created_idx
  on public.community_replies (topic_id, created_at);

create index community_topics_author_created_idx
  on public.community_topics (author_user_id, created_at desc)
  where author_user_id is not null;

create index community_replies_author_created_idx
  on public.community_replies (author_user_id, created_at desc)
  where author_user_id is not null;

create index community_notifications_recipient_created_idx
  on public.community_notifications (recipient_user_id, created_at desc);

create index community_notifications_recipient_unread_idx
  on public.community_notifications (recipient_user_id, created_at desc)
  where read_at is null;

create or replace function public.touch_community_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.validate_community_topic_references()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Keep status coherent when an FK action removes a canonical topic or an
  -- accepted reply. Explicit moderation updates already set both columns.
  if tg_op = 'UPDATE' then
    if old.duplicate_of_topic_id is not null
      and new.duplicate_of_topic_id is null
      and new.status = 'duplicate' then
      new.status := 'open';
    end if;

    if old.accepted_reply_id is not null
      and new.accepted_reply_id is null
      and new.status = 'resolved' then
      new.status := 'open';
    end if;
  end if;

  if new.accepted_reply_id is not null and not exists (
    select 1
    from public.community_replies r
    where r.id = new.accepted_reply_id
      and r.topic_id = new.id
      and r.status = 'published'
  ) then
    raise exception using errcode = '23514', message = 'Accepted reply must be a published reply on this topic';
  end if;

  if new.duplicate_of_topic_id is not null and not exists (
    select 1
    from public.community_topics target
    where target.id = new.duplicate_of_topic_id
      and target.status not in ('hidden', 'deleted', 'duplicate')
  ) then
    raise exception using errcode = '23514', message = 'Duplicate target must be an available canonical topic';
  end if;

  return new;
end;
$$;

create or replace function public.validate_community_reply_quote()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.quote_reply_id is not null and not exists (
    select 1
    from public.community_replies quoted
    where quoted.id = new.quote_reply_id
      and quoted.topic_id = new.topic_id
      and quoted.status <> 'hidden'
  ) then
    raise exception using errcode = '23514', message = 'Quoted reply must belong to the same topic';
  end if;

  return new;
end;
$$;

create trigger community_categories_touch_updated_at
before update on public.community_categories
for each row execute function public.touch_community_updated_at();

create trigger community_topics_touch_updated_at
before update on public.community_topics
for each row execute function public.touch_community_updated_at();

create trigger community_topics_validate_references
before insert or update of accepted_reply_id, duplicate_of_topic_id, status
on public.community_topics
for each row execute function public.validate_community_topic_references();

create trigger community_replies_touch_updated_at
before update on public.community_replies
for each row execute function public.touch_community_updated_at();

create trigger community_replies_validate_quote
before insert or update of quote_reply_id, topic_id
on public.community_replies
for each row execute function public.validate_community_reply_quote();

create trigger community_reports_touch_updated_at
before update on public.community_reports
for each row execute function public.touch_community_updated_at();

alter table public.community_categories enable row level security;
alter table public.community_topics enable row level security;
alter table public.community_replies enable row level security;
alter table public.community_tags enable row level security;
alter table public.community_topic_tags enable row level security;
alter table public.community_topic_entity_links enable row level security;
alter table public.community_reports enable row level security;
alter table public.community_subscriptions enable row level security;
alter table public.community_notifications enable row level security;
alter table public.community_moderators enable row level security;

create policy "community categories are publicly readable"
on public.community_categories for select to anon, authenticated
using (is_active);

create policy "community tags are publicly readable"
on public.community_tags for select to anon, authenticated
using (true);

create or replace function public.viewer_is_community_moderator()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.community_moderators moderator
      where moderator.user_id = auth.uid()
    );
$$;

create or replace view public.community_topics_public
with (security_barrier = true)
as
select
  topic.id,
  topic.kind,
  topic.title,
  topic.body,
  category.slug as category_slug,
  category.name_en as category_name_en,
  category.name_zh as category_name_zh,
  topic.status,
  (
    select count(*)::integer
    from public.community_replies reply_count_source
    where reply_count_source.topic_id = topic.id
      and reply_count_source.status in ('published', 'deleted')
  ) as reply_count,
  topic.accepted_reply_id,
  topic.duplicate_of_topic_id,
  case
    when duplicate_target.status = 'hidden' then null
    else duplicate_target.title
  end as duplicate_of_title,
  topic.source_type,
  case
    when topic.author_user_id = auth.uid() then 'You'
    when topic.author_user_id is null and topic.source_type = 'wechat_archive' then 'RunIPS Community Archive'
    when topic.author_user_id is null and topic.source_type = 'staff' then 'RunIPS team'
    when topic.author_user_id is null then 'Deleted member'
    else 'Community member'
  end as author_label,
  coalesce(topic.author_user_id = auth.uid(), false) as is_mine,
  (
    topic.kind = 'question'
    and topic.status in ('open', 'resolved')
    and auth.uid() is not null
    and (
      coalesce(topic.author_user_id = auth.uid(), false)
      or public.viewer_is_community_moderator()
    )
  ) as can_accept_solution,
  public.viewer_is_community_moderator() as can_moderate,
  (
    auth.uid() is not null
    and topic.status in ('open', 'resolved')
  ) as can_reply,
  (
    auth.uid() is not null
    and exists (
      select 1
      from public.community_subscriptions subscription
      where subscription.topic_id = topic.id
        and subscription.user_id = auth.uid()
    )
  ) as is_subscribed,
  coalesce(
    array(
      select tag.slug
      from public.community_topic_tags topic_tag
      join public.community_tags tag on tag.id = topic_tag.tag_id
      where topic_tag.topic_id = topic.id
      order by tag.slug
    ),
    '{}'::text[]
  ) as tags,
  topic.created_at,
  topic.updated_at,
  topic.last_activity_at
from public.community_topics topic
join public.community_categories category on category.id = topic.category_id
left join public.community_topics duplicate_target on duplicate_target.id = topic.duplicate_of_topic_id
where topic.status <> 'hidden'
   or public.viewer_is_community_moderator();

create or replace view public.community_replies_public
with (security_barrier = true)
as
select
  reply.id,
  reply.topic_id,
  reply.body,
  reply.quote_reply_id,
  reply.status,
  reply.source_type,
  case
    when reply.author_user_id = auth.uid() then 'You'
    when reply.author_user_id is null and reply.source_type = 'wechat_archive' then 'RunIPS Community Archive'
    when reply.author_user_id is null and reply.source_type = 'staff' then 'RunIPS team'
    when reply.author_user_id is null then 'Deleted member'
    else 'Community member'
  end as author_label,
  coalesce(reply.author_user_id = auth.uid(), false) as is_mine,
  coalesce(reply.author_user_id = topic.author_user_id, false) as is_topic_author,
  coalesce(topic.accepted_reply_id = reply.id, false) as is_accepted,
  public.viewer_is_community_moderator() as can_moderate,
  reply.created_at,
  reply.updated_at
from public.community_replies reply
join public.community_topics topic on topic.id = reply.topic_id
where (topic.status <> 'hidden' or public.viewer_is_community_moderator())
  and (reply.status <> 'hidden' or public.viewer_is_community_moderator());

create or replace view public.community_topic_entity_links_public
with (security_barrier = true)
as
select
  link.id,
  link.topic_id,
  link.entity_type,
  link.entity_key,
  link.label,
  link.url
from public.community_topic_entity_links link
join public.community_topics topic on topic.id = link.topic_id
where topic.status <> 'hidden'
   or public.viewer_is_community_moderator();

create or replace function public.create_community_topic(
  p_kind text,
  p_title text,
  p_body text,
  p_category_slug text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_kind text := lower(btrim(coalesce(p_kind, '')));
  normalised_title text := btrim(coalesce(p_title, ''));
  normalised_body text := btrim(coalesce(p_body, ''));
  normalised_category_slug text := lower(btrim(coalesce(p_category_slug, '')));
  selected_category_id smallint;
  new_topic_id bigint;
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(requesting_user::text));

  if normalised_kind not in ('question', 'discussion')
    and not (
      normalised_kind = 'guide'
      and public.viewer_is_community_moderator()
    ) then
    raise exception using errcode = '22023', message = 'Invalid community topic type';
  end if;

  if char_length(normalised_title) = 0 or char_length(normalised_title) > 160 then
    raise exception using errcode = '22023', message = 'Title must contain 1 to 160 characters';
  end if;

  if char_length(normalised_body) > 10000 then
    raise exception using errcode = '22023', message = 'Body must contain no more than 10000 characters';
  end if;

  select category.id
  into selected_category_id
  from public.community_categories category
  where category.slug = normalised_category_slug
    and category.is_active;

  if selected_category_id is null then
    raise exception using errcode = '22023', message = 'Invalid community category';
  end if;

  if (
    select count(*)
    from public.community_topics topic
    where topic.author_user_id = requesting_user
      and topic.created_at >= now() - interval '1 hour'
  ) >= 3 then
    raise exception using errcode = '54000', message = 'Topic creation rate limit reached';
  end if;

  if (
    select count(*)
    from public.community_topics topic
    where topic.author_user_id = requesting_user
      and topic.created_at >= now() - interval '24 hours'
  ) >= 10 then
    raise exception using errcode = '54000', message = 'Daily topic creation rate limit reached';
  end if;

  insert into public.community_topics (
    author_user_id,
    kind,
    category_id,
    title,
    body,
    source_type
  ) values (
    requesting_user,
    normalised_kind,
    selected_category_id,
    normalised_title,
    normalised_body,
    case when normalised_kind = 'guide' then 'staff' else 'user' end
  )
  returning id into new_topic_id;

  insert into public.community_subscriptions (topic_id, user_id)
  values (new_topic_id, requesting_user)
  on conflict do nothing;

  return new_topic_id;
end;
$$;

create or replace function public.create_community_reply(
  p_topic_id bigint,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_body text := btrim(coalesce(p_body, ''));
  new_reply_id bigint;
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(requesting_user::text));

  if char_length(normalised_body) = 0 or char_length(normalised_body) > 10000 then
    raise exception using errcode = '22023', message = 'Reply must contain 1 to 10000 characters';
  end if;

  if not exists (
    select 1
    from public.community_topics topic
    where topic.id = p_topic_id
      and topic.status in ('open', 'resolved')
  ) then
    raise exception using errcode = '22023', message = 'Topic is unavailable for replies';
  end if;

  if (
    select count(*)
    from public.community_replies reply
    where reply.author_user_id = requesting_user
      and reply.created_at >= now() - interval '1 hour'
  ) >= 20 then
    raise exception using errcode = '54000', message = 'Reply rate limit reached';
  end if;

  if (
    select count(*)
    from public.community_replies reply
    where reply.author_user_id = requesting_user
      and reply.created_at >= now() - interval '24 hours'
  ) >= 60 then
    raise exception using errcode = '54000', message = 'Daily reply rate limit reached';
  end if;

  insert into public.community_subscriptions (topic_id, user_id)
  values (p_topic_id, requesting_user)
  on conflict do nothing;

  insert into public.community_replies (
    topic_id,
    author_user_id,
    body,
    source_type
  ) values (
    p_topic_id,
    requesting_user,
    normalised_body,
    'user'
  )
  returning id into new_reply_id;

  update public.community_topics
  set last_activity_at = now()
  where id = p_topic_id;

  insert into public.community_notifications (
    recipient_user_id,
    actor_user_id,
    event_type,
    topic_id,
    reply_id
  )
  select
    subscription.user_id,
    requesting_user,
    'reply',
    p_topic_id,
    new_reply_id
  from public.community_subscriptions subscription
  where subscription.topic_id = p_topic_id
    and subscription.user_id <> requesting_user;

  return new_reply_id;
end;
$$;

create or replace function public.suggest_community_topics(
  p_query text,
  p_limit integer default 5
)
returns table (
  id bigint,
  kind text,
  title text,
  status text,
  category_slug text,
  category_name_en text,
  category_name_zh text,
  body_excerpt text,
  reply_count integer,
  accepted_reply_id bigint,
  duplicate_of_topic_id bigint,
  duplicate_of_title text,
  similarity_score real,
  last_activity_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  normalised_query text := btrim(coalesce(p_query, ''));
  result_limit integer := greatest(1, least(coalesce(p_limit, 5), 50));
begin
  if char_length(normalised_query) = 0 or char_length(normalised_query) > 160 then
    return;
  end if;

  return query
  select
    topic.id,
    topic.kind,
    topic.title,
    topic.status,
    category.slug,
    category.name_en,
    category.name_zh,
    left(topic.body, 240),
    (
      select count(*)::integer
      from public.community_replies reply
      where reply.topic_id = topic.id
        and reply.status in ('published', 'deleted')
    ),
    topic.accepted_reply_id,
    topic.duplicate_of_topic_id,
    case
      when duplicate_target.status = 'hidden' then null
      else duplicate_target.title
    end,
    least(
      1.0,
      0.70 * search_match.title_similarity
      + case when lower(topic.title) = lower(normalised_query) then 0.30 else 0 end
      + case when search_match.body_match then 0.15 else 0 end
      + case when search_match.tag_exact_match then 0.25 else 0 end
      + case when search_match.tag_partial_match then 0.10 else 0 end
    )::real,
    topic.last_activity_at
  from public.community_topics topic
  join public.community_categories category on category.id = topic.category_id
  left join public.community_topics duplicate_target on duplicate_target.id = topic.duplicate_of_topic_id
  cross join lateral (
    select
      extensions.similarity(lower(topic.title), lower(normalised_query)) as title_similarity,
      position(lower(normalised_query) in lower(topic.body)) > 0 as body_match,
      exists (
        select 1
        from public.community_topic_tags topic_tag
        join public.community_tags tag on tag.id = topic_tag.tag_id
        where topic_tag.topic_id = topic.id
          and (
            lower(tag.slug) = lower(normalised_query)
            or lower(tag.name) = lower(normalised_query)
          )
      ) as tag_exact_match,
      exists (
        select 1
        from public.community_topic_tags topic_tag
        join public.community_tags tag on tag.id = topic_tag.tag_id
        where topic_tag.topic_id = topic.id
          and (
            position(lower(normalised_query) in lower(tag.slug)) > 0
            or position(lower(normalised_query) in lower(tag.name)) > 0
          )
      ) as tag_partial_match
  ) search_match
  where topic.status not in ('hidden', 'deleted')
    and (
      search_match.title_similarity >= 0.12
      or position(lower(normalised_query) in lower(topic.title)) > 0
      or position(lower(topic.title) in lower(normalised_query)) > 0
      or search_match.body_match
      or search_match.tag_partial_match
    )
  order by
    (lower(topic.title) = lower(normalised_query)) desc,
    least(
      1.0,
      0.70 * search_match.title_similarity
      + case when lower(topic.title) = lower(normalised_query) then 0.30 else 0 end
      + case when search_match.body_match then 0.15 else 0 end
      + case when search_match.tag_exact_match then 0.25 else 0 end
      + case when search_match.tag_partial_match then 0.10 else 0 end
    ) desc,
    (topic.status <> 'duplicate') desc,
    (topic.status = 'resolved') desc,
    topic.last_activity_at desc
  limit result_limit;
end;
$$;

create or replace function public.mark_community_solution(
  p_topic_id bigint,
  p_reply_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  topic_author uuid;
  topic_kind text;
  topic_status text;
  reply_author uuid;
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  select topic.author_user_id, topic.kind, topic.status
  into topic_author, topic_kind, topic_status
  from public.community_topics topic
  where topic.id = p_topic_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Community topic was not found';
  end if;

  if requesting_user is distinct from topic_author
    and not public.viewer_is_community_moderator() then
    raise exception using errcode = '42501', message = 'Only the topic author or a moderator can choose a solution';
  end if;

  if topic_kind <> 'question' or topic_status not in ('open', 'resolved') then
    raise exception using errcode = '22023', message = 'This topic cannot accept a solution';
  end if;

  if p_reply_id is null then
    update public.community_topics
    set accepted_reply_id = null,
        status = 'open',
        last_activity_at = now()
    where id = p_topic_id;

    return null;
  end if;

  select reply.author_user_id
  into reply_author
  from public.community_replies reply
  where reply.id = p_reply_id
    and reply.topic_id = p_topic_id
    and reply.status = 'published';

  if not found then
    raise exception using errcode = '22023', message = 'Solution must be a published reply on this topic';
  end if;

  update public.community_topics
  set accepted_reply_id = p_reply_id,
      status = 'resolved',
      last_activity_at = now()
  where id = p_topic_id;

  if reply_author is not null and reply_author <> requesting_user then
    insert into public.community_notifications (
      recipient_user_id,
      actor_user_id,
      event_type,
      topic_id,
      reply_id
    ) values (
      reply_author,
      requesting_user,
      'solution',
      p_topic_id,
      p_reply_id
    );
  end if;

  return p_reply_id;
end;
$$;

create or replace function public.report_community_content(
  p_target_type text,
  p_target_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_target_type text := lower(btrim(coalesce(p_target_type, '')));
  normalised_reason text := btrim(coalesce(p_reason, ''));
  report_id bigint;
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(requesting_user::text));

  if normalised_target_type not in ('topic', 'reply') then
    raise exception using errcode = '22023', message = 'Invalid report target';
  end if;

  if char_length(normalised_reason) < 2 or char_length(normalised_reason) > 1000 then
    raise exception using errcode = '22023', message = 'Report reason must contain 2 to 1000 characters';
  end if;

  if (
    select count(*)
    from public.community_reports report
    where report.reporter_user_id = requesting_user
      and report.created_at >= now() - interval '1 hour'
  ) >= 10 then
    raise exception using errcode = '54000', message = 'Report rate limit reached';
  end if;

  if normalised_target_type = 'topic' then
    if not exists (
      select 1
      from public.community_topics topic
      where topic.id = p_target_id
        and topic.status not in ('hidden', 'deleted')
    ) then
      raise exception using errcode = 'P0002', message = 'Report target was not found';
    end if;

    insert into public.community_reports (
      reporter_user_id,
      topic_id,
      reason
    ) values (
      requesting_user,
      p_target_id,
      normalised_reason
    )
    on conflict (reporter_user_id, topic_id) where topic_id is not null
    do update set
      reason = excluded.reason,
      status = 'open',
      updated_at = now()
    returning id into report_id;
  else
    if not exists (
      select 1
      from public.community_replies reply
      join public.community_topics topic on topic.id = reply.topic_id
      where reply.id = p_target_id
        and reply.status = 'published'
        and topic.status <> 'hidden'
    ) then
      raise exception using errcode = 'P0002', message = 'Report target was not found';
    end if;

    insert into public.community_reports (
      reporter_user_id,
      reply_id,
      reason
    ) values (
      requesting_user,
      p_target_id,
      normalised_reason
    )
    on conflict (reporter_user_id, reply_id) where reply_id is not null
    do update set
      reason = excluded.reason,
      status = 'open',
      updated_at = now()
    returning id into report_id;
  end if;

  return report_id;
end;
$$;

create or replace function public.set_community_subscription(
  p_topic_id bigint,
  p_subscribed boolean
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  if coalesce(p_subscribed, false) then
    if not exists (
      select 1
      from public.community_topics topic
      where topic.id = p_topic_id
        and topic.status not in ('hidden', 'deleted')
    ) then
      raise exception using errcode = 'P0002', message = 'Community topic was not found';
    end if;

    insert into public.community_subscriptions (topic_id, user_id)
    values (p_topic_id, requesting_user)
    on conflict do nothing;
    return true;
  end if;

  delete from public.community_subscriptions
  where topic_id = p_topic_id
    and user_id = requesting_user;

  return false;
end;
$$;

create or replace function public.list_community_reports(
  p_status text default 'open',
  p_limit integer default 50
)
returns table (
  id bigint,
  target_type text,
  target_id bigint,
  topic_id bigint,
  reason text,
  status text,
  content_title text,
  content_excerpt text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_status text := lower(btrim(coalesce(p_status, 'open')));
  result_limit integer := greatest(1, least(coalesce(p_limit, 50), 200));
begin
  if requesting_user is null or not public.viewer_is_community_moderator() then
    raise exception using errcode = '42501', message = 'Community moderator access required';
  end if;

  if normalised_status not in ('open', 'resolved', 'dismissed', 'all') then
    raise exception using errcode = '22023', message = 'Invalid report status';
  end if;

  return query
  select
    report.id,
    case when report.topic_id is not null then 'topic' else 'reply' end,
    coalesce(report.topic_id, report.reply_id),
    coalesce(report.topic_id, reply.topic_id),
    report.reason,
    report.status,
    target_topic.title,
    case
      when report.topic_id is not null then left(coalesce(target_topic.body, ''), 500)
      else left(coalesce(reply.body, ''), 500)
    end,
    report.created_at,
    report.updated_at
  from public.community_reports report
  left join public.community_replies reply on reply.id = report.reply_id
  left join public.community_topics target_topic
    on target_topic.id = coalesce(report.topic_id, reply.topic_id)
  where normalised_status = 'all' or report.status = normalised_status
  order by report.created_at asc
  limit result_limit;
end;
$$;

create or replace function public.resolve_community_report(
  p_report_id bigint,
  p_action text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_action text := lower(btrim(coalesce(p_action, '')));
  target_topic_id bigint;
  target_reply_id bigint;
  next_report_status text;
begin
  if requesting_user is null or not public.viewer_is_community_moderator() then
    raise exception using errcode = '42501', message = 'Community moderator access required';
  end if;

  if normalised_action not in ('dismiss', 'resolve', 'hide') then
    raise exception using errcode = '22023', message = 'Invalid report action';
  end if;

  select report.topic_id, report.reply_id
  into target_topic_id, target_reply_id
  from public.community_reports report
  where report.id = p_report_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Community report was not found';
  end if;

  if normalised_action = 'hide' then
    if target_topic_id is not null then
      update public.community_topics
      set status = 'hidden',
          duplicate_of_topic_id = null,
          last_activity_at = now()
      where id = target_topic_id;
    else
      update public.community_topics topic
      set accepted_reply_id = null,
          status = case when topic.status = 'resolved' then 'open' else topic.status end,
          last_activity_at = now()
      where topic.accepted_reply_id = target_reply_id;

      update public.community_replies
      set status = 'hidden'
      where id = target_reply_id
        and status <> 'deleted';
    end if;

    next_report_status := 'resolved';
  elsif normalised_action = 'dismiss' then
    next_report_status := 'dismissed';
  else
    next_report_status := 'resolved';
  end if;

  update public.community_reports
  set status = next_report_status
  where id = p_report_id;

  return next_report_status;
end;
$$;

create or replace function public.list_community_notifications()
returns table (
  id bigint,
  event_type text,
  topic_id bigint,
  reply_id bigint,
  topic_title text,
  excerpt text,
  is_read boolean,
  read_at timestamptz,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  return query
  select
    notification.id,
    notification.event_type,
    notification.topic_id,
    notification.reply_id,
    case
      when topic.status = 'hidden' then 'Unavailable topic'
      else topic.title
    end,
    case
      when topic.status = 'hidden'
        or notification.reply_id is null
        or reply.status = 'hidden' then ''
      else left(reply.body, 240)
    end,
    notification.read_at is not null,
    notification.read_at,
    notification.created_at
  from public.community_notifications notification
  join public.community_topics topic on topic.id = notification.topic_id
  left join public.community_replies reply on reply.id = notification.reply_id
  where notification.recipient_user_id = requesting_user
  order by notification.created_at desc
  limit 100;
end;
$$;

create or replace function public.mark_community_notification_read(
  p_notification_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  update public.community_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id
    and recipient_user_id = requesting_user;

  return found;
end;
$$;

create or replace function public.moderate_community_topic(
  p_topic_id bigint,
  p_action text,
  p_duplicate_of_topic_id bigint default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_action text := lower(btrim(coalesce(p_action, '')));
  topic_author uuid;
  next_status text;
begin
  if requesting_user is null or not public.viewer_is_community_moderator() then
    raise exception using errcode = '42501', message = 'Community moderator access required';
  end if;

  select topic.author_user_id
  into topic_author
  from public.community_topics topic
  where topic.id = p_topic_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Community topic was not found';
  end if;

  if normalised_action = 'duplicate' then
    if p_duplicate_of_topic_id is null or p_duplicate_of_topic_id = p_topic_id then
      raise exception using errcode = '22023', message = 'A distinct duplicate target is required';
    end if;

    update public.community_topics
    set status = 'duplicate',
        duplicate_of_topic_id = p_duplicate_of_topic_id,
        accepted_reply_id = null,
        last_activity_at = now()
    where id = p_topic_id;
  elsif normalised_action = 'lock' then
    update public.community_topics
    set status = 'locked',
        duplicate_of_topic_id = null,
        last_activity_at = now()
    where id = p_topic_id;
  elsif normalised_action in ('unlock', 'reopen', 'unhide') then
    update public.community_topics
    set status = case when accepted_reply_id is null then 'open' else 'resolved' end,
        duplicate_of_topic_id = null,
        last_activity_at = now()
    where id = p_topic_id;
  elsif normalised_action = 'close' then
    update public.community_topics
    set status = 'closed',
        duplicate_of_topic_id = null,
        last_activity_at = now()
    where id = p_topic_id;
  elsif normalised_action = 'hide' then
    update public.community_topics
    set status = 'hidden',
        duplicate_of_topic_id = null,
        last_activity_at = now()
    where id = p_topic_id;
  else
    raise exception using errcode = '22023', message = 'Invalid moderation action';
  end if;

  select topic.status
  into next_status
  from public.community_topics topic
  where topic.id = p_topic_id;

  if topic_author is not null and topic_author <> requesting_user then
    insert into public.community_notifications (
      recipient_user_id,
      actor_user_id,
      event_type,
      topic_id
    ) values (
      topic_author,
      requesting_user,
      'topic_moderated',
      p_topic_id
    );
  end if;

  return next_status;
end;
$$;

create or replace function public.moderate_community_reply(
  p_reply_id bigint,
  p_action text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
  normalised_action text := lower(btrim(coalesce(p_action, '')));
  reply_topic_id bigint;
  next_status text;
begin
  if requesting_user is null or not public.viewer_is_community_moderator() then
    raise exception using errcode = '42501', message = 'Community moderator access required';
  end if;

  select reply.topic_id
  into reply_topic_id
  from public.community_replies reply
  where reply.id = p_reply_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Community reply was not found';
  end if;

  if normalised_action = 'hide' then
    update public.community_topics topic
    set accepted_reply_id = null,
        status = case when topic.status = 'resolved' then 'open' else topic.status end,
        last_activity_at = now()
    where topic.id = reply_topic_id
      and topic.accepted_reply_id = p_reply_id;

    update public.community_replies
    set status = 'hidden'
    where id = p_reply_id
      and status <> 'deleted';
  elsif normalised_action in ('restore', 'unhide') then
    update public.community_replies
    set status = 'published'
    where id = p_reply_id
      and status = 'hidden';
  else
    raise exception using errcode = '22023', message = 'Invalid reply moderation action';
  end if;

  select reply.status
  into next_status
  from public.community_replies reply
  where reply.id = p_reply_id;

  return next_status;
end;
$$;

revoke all on public.community_topics from public, anon, authenticated;
revoke all on public.community_replies from public, anon, authenticated;
revoke all on public.community_topic_tags from public, anon, authenticated;
revoke all on public.community_topic_entity_links from public, anon, authenticated;
revoke all on public.community_reports from public, anon, authenticated;
revoke all on public.community_subscriptions from public, anon, authenticated;
revoke all on public.community_notifications from public, anon, authenticated;
revoke all on public.community_moderators from public, anon, authenticated;

revoke all on public.community_categories from public, anon, authenticated;
grant select on public.community_categories to anon, authenticated;

revoke all on public.community_tags from public, anon, authenticated;
grant select on public.community_tags to anon, authenticated;

revoke all on sequence public.community_categories_id_seq from public, anon, authenticated;
revoke all on sequence public.community_topics_id_seq from public, anon, authenticated;
revoke all on sequence public.community_replies_id_seq from public, anon, authenticated;
revoke all on sequence public.community_tags_id_seq from public, anon, authenticated;
revoke all on sequence public.community_topic_entity_links_id_seq from public, anon, authenticated;
revoke all on sequence public.community_reports_id_seq from public, anon, authenticated;
revoke all on sequence public.community_notifications_id_seq from public, anon, authenticated;

grant select on public.community_topics_public to anon, authenticated;
grant select on public.community_replies_public to anon, authenticated;
grant select on public.community_topic_entity_links_public to anon, authenticated;

revoke all on function public.touch_community_updated_at() from public, anon, authenticated;
revoke all on function public.validate_community_topic_references() from public, anon, authenticated;
revoke all on function public.validate_community_reply_quote() from public, anon, authenticated;

revoke all on function public.viewer_is_community_moderator() from public, anon, authenticated;
grant execute on function public.viewer_is_community_moderator() to anon, authenticated;

revoke all on function public.create_community_topic(text, text, text, text) from public, anon, authenticated;
grant execute on function public.create_community_topic(text, text, text, text) to authenticated;

revoke all on function public.create_community_reply(bigint, text) from public, anon, authenticated;
grant execute on function public.create_community_reply(bigint, text) to authenticated;

revoke all on function public.suggest_community_topics(text, integer) from public, anon, authenticated;
grant execute on function public.suggest_community_topics(text, integer) to anon, authenticated;

revoke all on function public.mark_community_solution(bigint, bigint) from public, anon, authenticated;
grant execute on function public.mark_community_solution(bigint, bigint) to authenticated;

revoke all on function public.report_community_content(text, bigint, text) from public, anon, authenticated;
grant execute on function public.report_community_content(text, bigint, text) to authenticated;

revoke all on function public.set_community_subscription(bigint, boolean) from public, anon, authenticated;
grant execute on function public.set_community_subscription(bigint, boolean) to authenticated;

revoke all on function public.list_community_reports(text, integer) from public, anon, authenticated;
grant execute on function public.list_community_reports(text, integer) to authenticated;

revoke all on function public.resolve_community_report(bigint, text) from public, anon, authenticated;
grant execute on function public.resolve_community_report(bigint, text) to authenticated;

revoke all on function public.list_community_notifications() from public, anon, authenticated;
grant execute on function public.list_community_notifications() to authenticated;

revoke all on function public.mark_community_notification_read(bigint) from public, anon, authenticated;
grant execute on function public.mark_community_notification_read(bigint) to authenticated;

revoke all on function public.moderate_community_topic(bigint, text, bigint) from public, anon, authenticated;
grant execute on function public.moderate_community_topic(bigint, text, bigint) to authenticated;

revoke all on function public.moderate_community_reply(bigint, text) from public, anon, authenticated;
grant execute on function public.moderate_community_reply(bigint, text) to authenticated;

comment on view public.community_topics_public is
  'Public Community topics with no user UUIDs. Viewer-specific permissions are booleans only.';

comment on view public.community_replies_public is
  'Public Community replies with no user UUIDs. Deleted replies contain no original text.';

-- Extend the existing single-transaction erasure path. Community rows are
-- retained only as content-free tombstones where IDs are needed for thread
-- structure; no authored title, body, identity, or notification snapshot remains.
create or replace function public.delete_my_account(p_confirmation text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  requesting_user uuid := auth.uid();
begin
  if requesting_user is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  if p_confirmation is distinct from 'DELETE MY ACCOUNT' then
    raise exception using errcode = '22023', message = 'Confirmation text does not match';
  end if;

  -- Serialise against Community topic/reply/report creation by this account so
  -- no authored content can appear after the scrub phase has passed.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(requesting_user::text));

  delete from public.feedback_submissions
  where user_id = requesting_user;

  -- Remove notifications owned by the account and notifications pointing to
  -- content authored by it before that content is scrubbed.
  delete from public.community_notifications notification
  where notification.recipient_user_id = requesting_user
     or notification.actor_user_id = requesting_user
     or exists (
       select 1
       from public.community_topics topic
       where topic.id = notification.topic_id
         and topic.author_user_id = requesting_user
     )
     or exists (
       select 1
       from public.community_replies reply
       where reply.id = notification.reply_id
         and reply.author_user_id = requesting_user
     );

  delete from public.community_reports report
  where report.reporter_user_id = requesting_user
     or exists (
       select 1
       from public.community_topics topic
       where topic.id = report.topic_id
         and topic.author_user_id = requesting_user
     )
     or exists (
       select 1
       from public.community_replies reply
       where reply.id = report.reply_id
         and reply.author_user_id = requesting_user
     );

  delete from public.community_subscriptions subscription
  where subscription.user_id = requesting_user
     or exists (
       select 1
       from public.community_topics topic
       where topic.id = subscription.topic_id
         and topic.author_user_id = requesting_user
     );

  delete from public.community_topic_tags topic_tag
  where exists (
    select 1
    from public.community_topics topic
    where topic.id = topic_tag.topic_id
      and topic.author_user_id = requesting_user
  );

  delete from public.community_topic_entity_links link
  where exists (
    select 1
    from public.community_topics topic
    where topic.id = link.topic_id
      and topic.author_user_id = requesting_user
  );

  -- A deleted reply cannot remain an accepted solution on somebody else's
  -- question. Return such questions to open before scrubbing the reply.
  update public.community_topics topic
  set accepted_reply_id = null,
      status = case when topic.status = 'resolved' then 'open' else topic.status end,
      last_activity_at = now()
  where exists (
    select 1
    from public.community_replies reply
    where reply.id = topic.accepted_reply_id
      and reply.author_user_id = requesting_user
  );

  -- If a canonical topic disappears, reopen its duplicates rather than leave
  -- them pointing at a content-free tombstone.
  update public.community_topics topic
  set duplicate_of_topic_id = null,
      status = case when topic.accepted_reply_id is null then 'open' else 'resolved' end,
      last_activity_at = now()
  where exists (
    select 1
    from public.community_topics deleted_topic
    where deleted_topic.id = topic.duplicate_of_topic_id
      and deleted_topic.author_user_id = requesting_user
  );

  update public.community_replies
  set author_user_id = null,
      body = '',
      quote_reply_id = null,
      status = 'deleted',
      source_type = 'user'
  where author_user_id = requesting_user;

  update public.community_topics
  set author_user_id = null,
      title = 'Deleted topic',
      body = '',
      status = 'deleted',
      accepted_reply_id = null,
      duplicate_of_topic_id = null,
      source_type = 'user',
      source_note = null,
      last_activity_at = now()
  where author_user_id = requesting_user;

  delete from public.community_moderators
  where user_id = requesting_user;

  update public.community_moderators
  set created_by = null
  where created_by = requesting_user;

  delete from auth.audit_log_entries
  where payload ->> 'actor_id' = requesting_user::text;

  delete from auth.users
  where id = requesting_user;

  if not found then
    raise exception using errcode = 'P0002', message = 'Account was not found';
  end if;
end;
$$;

revoke all on function public.delete_my_account(text) from public, anon, authenticated;
grant execute on function public.delete_my_account(text) to authenticated;

comment on function public.delete_my_account(text) is
  'Permanently deletes the authenticated account, scrubs authored Community content, and removes all linked live data.';
