-- Professor/supervisor reviews for the self-hosted RunIPS backend.
-- Public views deliberately omit user_id so published reviews stay anonymous.

create table if not exists public.professor_reviews (
  id bigint generated by default as identity primary key,
  professor_id bigint not null references public.professors(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  overall_rating smallint not null check (overall_rating between 1 and 5),
  pressure_rating smallint not null check (pressure_rating between 1 and 5),
  supervision_rating smallint not null check (supervision_rating between 1 and 5),
  communication_rating smallint not null check (communication_rating between 1 and 5),
  autonomy_rating smallint not null check (autonomy_rating between 1 and 5),
  lab_culture_rating smallint not null check (lab_culture_rating between 1 and 5),
  research_support_rating smallint not null check (research_support_rating between 1 and 5),
  career_support_rating smallint not null check (career_support_rating between 1 and 5),
  would_choose_again boolean not null,
  student_level text not null check (student_level in ('masters', 'doctoral', 'researchStudent', 'other')),
  relationship_status text not null check (relationship_status in ('current', 'former')),
  communication_language text not null check (communication_language in ('ja', 'en', 'zh', 'mixed', 'other')),
  tags text[] not null default '{}'::text[] check (cardinality(tags) <= 3),
  comment text not null check (char_length(comment) between 30 and 2000),
  status text not null default 'published' check (status in ('pending', 'published', 'rejected', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (professor_id, user_id)
);

create index if not exists professor_reviews_professor_created_idx
  on public.professor_reviews (professor_id, created_at desc)
  where status = 'published';

create table if not exists public.professor_review_votes (
  review_id bigint not null references public.professor_reviews(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table if not exists public.professor_review_reports (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.professor_reviews(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 2 and 500),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (review_id, user_id)
);

create or replace function public.touch_professor_review_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists professor_reviews_touch_updated_at on public.professor_reviews;
create trigger professor_reviews_touch_updated_at
before update on public.professor_reviews
for each row execute function public.touch_professor_review_updated_at();

drop trigger if exists professor_review_votes_touch_updated_at on public.professor_review_votes;
create trigger professor_review_votes_touch_updated_at
before update on public.professor_review_votes
for each row execute function public.touch_professor_review_updated_at();

alter table public.professor_reviews enable row level security;
alter table public.professor_review_votes enable row level security;
alter table public.professor_review_reports enable row level security;

drop policy if exists "review owners can read their review" on public.professor_reviews;
create policy "review owners can read their review"
on public.professor_reviews for select to authenticated
using (user_id = auth.uid());

drop policy if exists "authenticated users can create their review" on public.professor_reviews;
create policy "authenticated users can create their review"
on public.professor_reviews for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "review owners can update their review" on public.professor_reviews;
create policy "review owners can update their review"
on public.professor_reviews for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "review owners can delete their review" on public.professor_reviews;
create policy "review owners can delete their review"
on public.professor_reviews for delete to authenticated
using (user_id = auth.uid());

drop policy if exists "users can read their review votes" on public.professor_review_votes;
create policy "users can read their review votes"
on public.professor_review_votes for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users can create their review votes" on public.professor_review_votes;
create policy "users can create their review votes"
on public.professor_review_votes for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "users can update their review votes" on public.professor_review_votes;
create policy "users can update their review votes"
on public.professor_review_votes for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "users can delete their review votes" on public.professor_review_votes;
create policy "users can delete their review votes"
on public.professor_review_votes for delete to authenticated
using (user_id = auth.uid());

drop policy if exists "users can create review reports" on public.professor_review_reports;
create policy "users can create review reports"
on public.professor_review_reports for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "users can read their review reports" on public.professor_review_reports;
create policy "users can read their review reports"
on public.professor_review_reports for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users can update their review reports" on public.professor_review_reports;
create policy "users can update their review reports"
on public.professor_review_reports for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace view public.professor_reviews_public
with (security_barrier = true)
as
select
  r.id,
  r.professor_id,
  r.overall_rating,
  r.pressure_rating,
  r.supervision_rating,
  r.communication_rating,
  r.autonomy_rating,
  r.lab_culture_rating,
  r.research_support_rating,
  r.career_support_rating,
  r.would_choose_again,
  r.student_level,
  r.relationship_status,
  r.communication_language,
  r.tags,
  r.comment,
  r.created_at,
  r.updated_at,
  count(*) filter (where v.value = 1)::integer as helpful_count,
  count(*) filter (where v.value = -1)::integer as unhelpful_count
from public.professor_reviews r
left join public.professor_review_votes v on v.review_id = r.id
where r.status = 'published'
group by r.id;

create or replace view public.professor_review_summaries
with (security_barrier = true)
as
select
  professor_id,
  count(*)::integer as review_count,
  round(avg(overall_rating)::numeric, 1) as overall_average,
  round(avg(pressure_rating)::numeric, 1) as pressure_average,
  round((100.0 * count(*) filter (where would_choose_again) / nullif(count(*), 0))::numeric, 0) as would_choose_again_percent,
  round(avg(supervision_rating)::numeric, 1) as supervision_average,
  round(avg(communication_rating)::numeric, 1) as communication_average,
  round(avg(autonomy_rating)::numeric, 1) as autonomy_average,
  round(avg(lab_culture_rating)::numeric, 1) as lab_culture_average,
  round(avg(research_support_rating)::numeric, 1) as research_support_average,
  round(avg(career_support_rating)::numeric, 1) as career_support_average
from public.professor_reviews
where status = 'published'
group by professor_id;

revoke all on public.professor_reviews from anon;
revoke all on public.professor_review_votes from anon;
revoke all on public.professor_review_reports from anon;
grant select, insert, update, delete on public.professor_reviews to authenticated;
grant select, insert, update, delete on public.professor_review_votes to authenticated;
grant select, insert, update on public.professor_review_reports to authenticated;
grant usage, select on sequence public.professor_reviews_id_seq to authenticated;
grant usage, select on sequence public.professor_review_reports_id_seq to authenticated;
grant select on public.professor_reviews_public to anon, authenticated;
grant select on public.professor_review_summaries to anon, authenticated;
